#  ____   __     __  ____     ____                   _                    _
# |  _ \  \ \   / / |  _ \   / ___|   ___    _ __   | |_   _ __    ___   | |
# | |_) |  \ \ / /  | |_) | | |      / _ \  | '_ \  | __| | '__|  / _ \  | |
# |  __/    \ V /   |  __/  | |___  | (_) | | | | | | |_  | |    | (_) | | |
# |_|        \_/    |_|      \____|  \___/  |_| |_|  \__| |_|     \___/  |_|
#                                                                             by IdkMan

General:
  # Here you can change language of the plugin, currenty supported languages: EN, PL.
  # If you want to add your own language just fill `language/en.yml` file and contact with me on spigot @IdkMan.
  Language: EN


PVP:
  # How long PVP mode should be active?
  TimeInPVP: 15
  # Turn off *fly* on pvp.
  TurnOffFlyOnPVP: true
  # Disable potion invisibility. Does not disable vanish!
  DisableInvisibilityOnPVP: false
  # Should all commands be blocked during PVP?
  BlockAllCommandsOnPVP: false
  # Should we block any kind of teleport?
  # This includes chorus fruit, ender pearl, command teleport (/tpa accept) and all 3rd party plugins with teleport.
  BlockAnyKindOfTeleportOnPVP: false
  # Should we block chorus fruit teleport?
  # If *BlockAnyKindOfTeleportOnPVP* option is set to TRUE then this option will be ignored.
  BlockChorusFruitTeleport: true
  # Should we block ender pearl teleport?
  # If *BlockAnyKindOfTeleportOnPVP* option is set to TRUE then this option will be ignored.
  BlockEnderPeralTeleport: true
  # Should player be killed when logged out during PVP?
  KillOnLogoutDuringPVP: true
  # Should items be dropped on the ground when player is killed?
  # This applies only for the situation where player is killed because he logged out.
  # This option will be ignored if *KillWhenLogoutOnPVP* option is set to FALSE.
  DropItemsOnKill: true
  # Should we broadcast info to all players, that the player logged out during PVP?
  # This option will be ignored if *KillWhenLogoutOnPVP* option is set to FALSE.
  BroadcastPlayerLoggedOutOnPVP: true
  # All commands that will be executed in console when player log out during PVP. You can use %player% variable.
  # Commands should be written without a preceding slash "/"
  # Example: - eco set %player% 0
  CommandsExecutedWhenLogoutInPVP: []
  # If *BlockAllCommandsOnPVP* option is set to FALSE then you can define below commands that will be blocked during PVP.
  # If *BlockAllCommandsOnPVP* option is set to TRUE then this option will be ignored.
  # You don't need to care about case sensitive!
  # Example: - tpa
  BlockOnlySelectedCommandsOnPVP:
    - tpa
    - tpayes
    - tpyes
    - tpaccept
    - tpadeny
    - tpdeny
    - tp
    - teleport


Hooks:
  # Turn off god mode when the player is attacked.
  # Works only when supported version of EssentialsX is installed on the server.
  DisableEssentialsGodModeOnHit: false


# Not enough features? Let me know what you want! Write private message to me on spigot @IdkMan
# or describe your problem on discussion page of this plugin.

